ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('servicios.urls')),
    path('', include('ProyectoWebApp.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('pedidos/', include('pedidos.urls')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog, name='Blog'),
    path('categoria/<int:categoria_id>', views.categoria, name='Categoria'),

]

carro/urls.py
from django.urls import path
from . import views

app_name = 'carro'

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),

]

pedidos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.procesar_pedido, name='procesar_pedido'),

]

tienda/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.tienda, name='Tienda'),

]

pedidos/models.py
from django.db import models
from django.contrib.auth import get_user_model
from tienda.models import Producto
from django.db.models import F, Sum, FloatField
# Create your models here.

User = get_user_model() # Usuario activo

class Pedido(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add= True)

    def __str__(self):
        return f'{self.id}'
    
    @property
    def total(self):
        return self.lineapedido_set.aggregate(
            total = Sum(F('precio')*F('cantidad'), output_field=FloatField())
        )['total']

    class Meta:
        db_table = 'pedidos'
        verbose_name = 'pedido'
        verbose_name_plural = 'pedidos'
        ordering = ['id']

class LineaPedido(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=1)
    precio = models.FloatField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add= True)

    def __str__(self):
        return f'{self.cantidad} unidades de {self.producto.nombre}'
    
    class Meta:
        db_table = 'lineapedidos'
        verbose_name = 'Línea Pedido'
        verbose_name_plural = 'Líneas Pedidos'
        ordering = ['id']

tienda/models.py
from django.db import models

# Create your models here.
class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Categoría Producto'
        verbose_name_plural = 'Categorías de los Productos'

    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    categorias = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='tienda', null=True, blank=True)
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default= True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

pedidos/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import send_mail
from carro.carro import Carro
from django.contrib import messages
from .models import LineaPedido, Pedido

# Create your views here.

@login_required(login_url='/autenticacion/logear')
def procesar_pedido(request):
    pedido = Pedido.objects.create(user= request.user)
    carro = Carro(request)

    lineas_pedidos = list()
    for key, value in carro.carro.items():
        lineas_pedidos.append(LineaPedido(
            producto_id = key,
            cantidad = value['cantidad'],
            precio = float(value['precio']),
            user = request.user,
            pedido_id = pedido.id
        ))
    
    LineaPedido.objects.bulk_create(lineas_pedidos)
    print("El precio es: ", lineas_pedidos[0].precio)
    enviar_mail(
        pedido = pedido,
        lineas_pedidos = lineas_pedidos,
        nombreusuario = request.user.username,
        emailusuario = request.user.email
    )
    # print("El total es:",pedido.total)
    messages.success(request, 'El pedido se ha creado correctamente')

    return redirect('Tienda')

def enviar_mail(**kwargs):
    asunto = 'Gracias por el pedido'
    mensaje = render_to_string(
        'pedido.html',
        {
            'pedido': kwargs.get('pedido'),
            'lineas_pedidos': kwargs.get('lineas_pedidos'),
            'nombreusuario': kwargs.get('nombreusuario'),
            'emailusuario': kwargs.get('emailusuario')
        }
    )

    mensaje_texto = strip_tags(mensaje)
    from_email = 'correodepruebas9829@gmail.com'
    to=kwargs.get('emailusuario')
    # to = 'ricardo060498@gmail.com'
    send_mail(asunto, mensaje_texto, from_email, [to], html_message=mensaje)

tienda/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.
def tienda(request):
    productos = Producto.objects.all()
    return render(request, 'tienda.html', {'productos': productos})

tienda/templates/pedido.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Hola {{nombreusuario}} <br>
    N° de pedido: {{pedido.id}} <br>
    Email del usuario: {{emailusuario}} <br>
    Líneas de pedido: {{lineas_pedidos}}
</body>
</html>

tienda/templates/tienda.html
{% extends "ProyectoWebApp/base.html" %}

{% load static %}

{% block content %}

<style>
    @media (max-width: 576px) {

        .card {

            margin: 0 10px;
            /* Pequeño margen a los lados */

        }

        .btn-success {

            padding: 8px 16px;
            /* Botón más compacto */

            font-size: 14px;

        }

    }
</style>

<div class="container" style="margin: 5px auto;">

    <div class="row">

        <!-- Columna principal para productos -->

        <div class="col-lg-9 col-md-12 order-md-1 order-2">

            <div class="row">

                {% for producto in productos %}

                <div class="col-xl-4 col-lg-6 col-md-6 col-sm-6 mb-4">

                    <div class="card h-100">

                        <img src="{{producto.imagen.url}}" alt="" class="card-img-top"
                            style="object-fit: cover; height: 250px;"
                            srcset="{{producto.imagen.url}} 600w, {{producto.imagen_mobile.url}} 300w"
                            sizes="(max-width: 576px) 300px, 600px">



                        <div class="card-body d-flex flex-column">

                            <h5 class="card-title">{{producto.nombre}}</h5>

                            <p class="card-text mt-auto">S/. {{producto.precio}}</p>

                        </div>



                        <div class="card-footer text-center">

                            <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al
                                carrito</a>

                        </div>

                    </div>

                </div>

                {% endfor %}

            </div>

        </div>

        <!-- Columna para el carrito -->

        <div class="col-lg-3 col-md-12 order-md-2 order-1 mb-4">

            {% if request.user.is_authenticated %}

            {% include 'widget.html' %}

            {% else %}

            <div class="alert alert-danger text-center">Hacer Login</div>

            {% endif %}

        </div>

    </div>

</div>

{% endblock %}

tienda/templates/widget.html
<table class="table table-bordered" style="color: white;">
    <thead>
        <tr>
            <th colspan="3" class="text-center">
                <div class="d-flex justify-content-between align-items-center">
                    {% if request.session.carro.items %}
                        <span class="flex-grow-1 text-center">Carro compras</span>
                        <a href="{% url 'carro:limpiar' %}" class="btn btn-sm btn-primary">Limpiar carrito</a>
                    {% else %}
                        <span class="w-100 text-center">Carro compras</span>
                    {% endif %}
                </div>
            </th>
        </tr>

        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Monto</th>
        </tr>
    </thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <div class="d-flex flex-column align-items-center">
                            <div class="d-flex mb-1">
                                <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success mx-1">+</a>
                                <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success mx-1">-</a><br>
                                <a href="{% url 'carro:eliminar' value.producto_id %}" class="btn btn-sm btn-danger mx-1">x</a><br>
                            </div>
                              <div>S/. {{value.precio}}</div>
                        </div>
                    </td>
                </tr>
            {% endfor %}

        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin productos
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">
                Total: S/. {{importe_total_carro}}
            </td>
        </tr>

        {% if request.session.carro.items %}
            <tr>
                <td colspan="3" style="text-align: center;">
                    <a href="{% url 'procesar_pedido' %}" class="btn btn-success">Hacer Pedido</a>
                </td>
            </tr>
        {% endif %}
    </tfoot>
</table>